# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d5217873b013eb857bdfcc942cf4e001689791ffd6c968817c40b43915b2afe7f4cdc7e53db1b29f2bcce92f9ae9abb734b90651802787ca3f8f54f256e0a2

test:
  secret_key_base: c08459d92c7298555aedb12683cd46be00457f051be0aabacfcc051cb01bc5be3ecf1e75663eccc983fdd904ffc49ff0a77fbf996cb84d165085b2be68c9197b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
